name: Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Setup Node 15
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Documentation
        run: yarn docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
