name: ESLint

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Setup Node 15
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install Dependencies
        run: yarn

      - name: Run ESLint
        run: yarn lint
